### ISSUE TITLE
Cannot import name_remove_dead_weakref

### ISSUE THREAD

**Issue by Drodriguez819** [tmercswims/fishgame#1]
Have been getting Cannot import name_remove_dead_weakref when importing new version of fishgame to upgrade . Any thoughts ?

**Comment by tmercswims** [comment]
Sorry I didn't reply sooner, I completely missed this!

Are you still facing this issue? I've never seen it before, so I'm not entirely sure what's happening. If you're still seeing the issue then we can try some general troubleshooting:
- Restart your bot.
- Reload the script.
- Open the script directory and make sure there aren't two fishgame scripts - there was a mistake in one of the releases which caused the script to unpack into the script directory, rather than a directory _within_ the script directory. If that's the case, keep just the one in its own directory, e.g. `<script dir>/fishgame/`.

**Comment by tmercswims** [comment]
I'm going to close this as stale. Please open a new issue if you face this again, and provide as much detail as you can. Thank you!
