### ISSUE TITLE
Is it possible to add the script to streamer bot?

### ISSUE THREAD

**Issue by IEpicDestiny** [tmercswims/fishgame#4]
Hi does the script ONLY work with Streamlabs chatbot or can it work with streamer bot also?

**Comment by tmercswims** [comment]
As it is this will only work with Streamabs Chatbot. It depends a lot on the Streamlabs Chatbot environment to function correctly.

**Comment by IEpicDestiny** [comment]
Is there at least a way I could change the script so that it gives Streamelements points instead of Streamlabs points?

**Comment by tmercswims** [comment]
I did some cursory looking, and it doesn't seem like the StreamElements chat bot supports plugins, so for that reason alone it actually isn't possible to use something akin to this in a StreamElements context.

The reason it can be done with Streamlabs Chatbot is because you host the instance of the bot yourself, so you can add plugins that come with code and provide additional functionality.
